version: "3.8"

services:
  jenkins:
    image: jenkins/jenkins:lts-jdk11
    container_name: jenkins
    volumes:
      - jenkinsdata:/var/jenkins_home
    ports:
      - "9090:8080"

networks:
  jenkins-network:
    driver: bridge

volumes:
  jenkinsdata:
