version: "3.8"

services:
  kafka1:
    image: bitnami/kafka:3.4.0
    container_name: kafka1
    volumes:
      - kafka1:/bitnami/kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_ENABLE_KRAFT: yes
      ALLOW_PLAINTEXT_LISTENER: yes
      KAFKA_CFG_PROCESS_ROLES: broker,controller
      KAFKA_CFG_NODE_ID: 1
      KAFKA_CFG_CONTROLLER_QUORUM_VOTERS: 1@kafka1:19092,2@kafka2:19093,3@kafka3:19094
      KAFKA_CFG_LISTENERS: PLAINTEXT://:29092,CONTROLLER://:19092,EXTERNAL://:9092
      KAFKA_CFG_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_CFG_ADVERTISED_LISTENERS: PLAINTEXT://kafka1:29092,EXTERNAL://localhost:9092
      KAFKA_CFG_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT,EXTERNAL:PLAINTEXT
      KAFKA_HEAP_OPTS: -Xmx512m -Xms512m
      KAFKA_KRAFT_CLUSTER_ID: c1WknUJyRei9JELTjtbe-w

  kafka2:
    image: bitnami/kafka:3.4.0
    container_name: kafka2
    volumes:
      - kafka2:/bitnami/kafka
    ports:
      - "9093:9093"
    environment:
      KAFKA_ENABLE_KRAFT: yes
      ALLOW_PLAINTEXT_LISTENER: yes
      KAFKA_CFG_PROCESS_ROLES: broker,controller
      KAFKA_CFG_NODE_ID: 2
      KAFKA_CFG_CONTROLLER_QUORUM_VOTERS: 1@kafka1:19092,2@kafka2:19093,3@kafka3:19094
      KAFKA_CFG_LISTENERS: PLAINTEXT://:29093,CONTROLLER://:19093,EXTERNAL://:9093
      KAFKA_CFG_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_CFG_ADVERTISED_LISTENERS: PLAINTEXT://kafka2:29093,EXTERNAL://localhost:9093
      KAFKA_CFG_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT,EXTERNAL:PLAINTEXT
      KAFKA_HEAP_OPTS: -Xmx512m -Xms512m
      KAFKA_KRAFT_CLUSTER_ID: c1WknUJyRei9JELTjtbe-w

  kafka3:
    image: bitnami/kafka:3.4.0
    container_name: kafka3
    volumes:
      - kafka3:/bitnami/kafka
    ports:
      - "9094:9094"
    environment:
      KAFKA_ENABLE_KRAFT: yes
      ALLOW_PLAINTEXT_LISTENER: yes
      KAFKA_CFG_PROCESS_ROLES: broker,controller
      KAFKA_CFG_NODE_ID: 3
      KAFKA_CFG_CONTROLLER_QUORUM_VOTERS: 1@kafka1:19092,2@kafka2:19093,3@kafka3:19094
      KAFKA_CFG_LISTENERS: PLAINTEXT://:29094,CONTROLLER://:19094,EXTERNAL://:9094
      KAFKA_CFG_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_CFG_ADVERTISED_LISTENERS: PLAINTEXT://kafka3:29094,EXTERNAL://localhost:9094
      KAFKA_CFG_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT,EXTERNAL:PLAINTEXT
      KAFKA_HEAP_OPTS: -Xmx512m -Xms512m
      KAFKA_KRAFT_CLUSTER_ID: c1WknUJyRei9JELTjtbe-w

networks:
  kafka:
    driver: bridge

volumes:
  kafka1:
    name: kafka1
  kafka2:
    name: kafka2
  kafka3:
    name: kafka3